/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ComplianceModule__factory } from "./ComplianceModule__factory";
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
