/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assets from "./assets";
export type { assets };
import type * as identity from "./identity";
export type { identity };
import type * as mocks from "./mocks";
export type { mocks };
import type * as token from "./token";
export type { token };
import type * as vault from "./vault";
export type { vault };
