/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IIdentityRegistry {
  export type IdentityStruct = {
    exists: boolean;
    frozen: boolean;
    tier: BigNumberish;
    subTier: BigNumberish;
    group: BytesLike;
    subGroup: BytesLike;
    expirationTime: BigNumberish;
    kycHash: BytesLike;
    cvRecordId: string;
  };

  export type IdentityStructOutput = [
    exists: boolean,
    frozen: boolean,
    tier: bigint,
    subTier: bigint,
    group: string,
    subGroup: string,
    expirationTime: bigint,
    kycHash: string,
    cvRecordId: string
  ] & {
    exists: boolean;
    frozen: boolean;
    tier: bigint;
    subTier: bigint;
    group: string;
    subGroup: string;
    expirationTime: bigint;
    kycHash: string;
    cvRecordId: string;
  };
}

export interface IIdentityRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getIdentity" | "isVerified"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IdentityFrozen"
      | "IdentityRegistered"
      | "IdentityUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
}

export namespace IdentityFrozenEvent {
  export type InputTuple = [
    wallet: AddressLike,
    frozen: boolean,
    reason: string
  ];
  export type OutputTuple = [wallet: string, frozen: boolean, reason: string];
  export interface OutputObject {
    wallet: string;
    frozen: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    cvRecordId: string,
    tier: BigNumberish
  ];
  export type OutputTuple = [wallet: string, cvRecordId: string, tier: bigint];
  export interface OutputObject {
    wallet: string;
    cvRecordId: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    tier: BigNumberish,
    frozen: boolean
  ];
  export type OutputTuple = [wallet: string, tier: bigint, frozen: boolean];
  export interface OutputObject {
    wallet: string;
    tier: bigint;
    frozen: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getIdentity: TypedContractMethod<
    [wallet: AddressLike],
    [IIdentityRegistry.IdentityStructOutput],
    "view"
  >;

  isVerified: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getIdentity"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [IIdentityRegistry.IdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  getEvent(
    key: "IdentityFrozen"
  ): TypedContractEvent<
    IdentityFrozenEvent.InputTuple,
    IdentityFrozenEvent.OutputTuple,
    IdentityFrozenEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;

  filters: {
    "IdentityFrozen(address,bool,string)": TypedContractEvent<
      IdentityFrozenEvent.InputTuple,
      IdentityFrozenEvent.OutputTuple,
      IdentityFrozenEvent.OutputObject
    >;
    IdentityFrozen: TypedContractEvent<
      IdentityFrozenEvent.InputTuple,
      IdentityFrozenEvent.OutputTuple,
      IdentityFrozenEvent.OutputObject
    >;

    "IdentityRegistered(address,string,uint16)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityUpdated(address,uint16,bool)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
  };
}
