/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockCleanverseValidator } from "./MockCleanverseValidator";
export type { MockUSDC } from "./MockUSDC";
