/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockCleanverseValidator {
  export type PoolRuleStruct = {
    allowedGroup: BytesLike;
    allowedSubGroup: BytesLike;
    minTier: BigNumberish;
    minSubTier: BigNumberish;
  };

  export type PoolRuleStructOutput = [
    allowedGroup: string,
    allowedSubGroup: string,
    minTier: bigint,
    minSubTier: bigint
  ] & {
    allowedGroup: string;
    allowedSubGroup: string;
    minTier: bigint;
    minSubTier: bigint;
  };
}

export interface MockCleanverseValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRule"
      | "isPaused"
      | "isRegister"
      | "poolPaused"
      | "register"
      | "registered"
      | "ruleCount"
      | "setPaused"
      | "syncUser"
      | "userGroup"
      | "userHasApass"
      | "userTier"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PoolPaused" | "PoolRegistered" | "RuleAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRule",
    values: [AddressLike, MockCleanverseValidator.PoolRuleStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegister",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, MockCleanverseValidator.PoolRuleStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaused",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "syncUser",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userGroup",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userHasApass",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTier",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRegister", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ruleCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "syncUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userGroup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userHasApass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userTier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace PoolPausedEvent {
  export type InputTuple = [pool: AddressLike, paused: boolean];
  export type OutputTuple = [pool: string, paused: boolean];
  export interface OutputObject {
    pool: string;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolRegisteredEvent {
  export type InputTuple = [pool: AddressLike];
  export type OutputTuple = [pool: string];
  export interface OutputObject {
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleAddedEvent {
  export type InputTuple = [pool: AddressLike, minTier: BigNumberish];
  export type OutputTuple = [pool: string, minTier: bigint];
  export interface OutputObject {
    pool: string;
    minTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockCleanverseValidator extends BaseContract {
  connect(runner?: ContractRunner | null): MockCleanverseValidator;
  waitForDeployment(): Promise<this>;

  interface: MockCleanverseValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRule: TypedContractMethod<
    [pool: AddressLike, rule: MockCleanverseValidator.PoolRuleStruct],
    [void],
    "nonpayable"
  >;

  isPaused: TypedContractMethod<[pool: AddressLike], [boolean], "view">;

  isRegister: TypedContractMethod<[pool: AddressLike], [boolean], "view">;

  poolPaused: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  register: TypedContractMethod<
    [pool: AddressLike, rule: MockCleanverseValidator.PoolRuleStruct],
    [void],
    "nonpayable"
  >;

  registered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  ruleCount: TypedContractMethod<[pool: AddressLike], [bigint], "view">;

  setPaused: TypedContractMethod<
    [pool: AddressLike, paused_: boolean],
    [void],
    "nonpayable"
  >;

  syncUser: TypedContractMethod<
    [
      pool: AddressLike,
      user: AddressLike,
      tier: BigNumberish,
      group: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userGroup: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [string],
    "view"
  >;

  userHasApass: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  userTier: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  verify: TypedContractMethod<
    [pool: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRule"
  ): TypedContractMethod<
    [pool: AddressLike, rule: MockCleanverseValidator.PoolRuleStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[pool: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegister"
  ): TypedContractMethod<[pool: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolPaused"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [pool: AddressLike, rule: MockCleanverseValidator.PoolRuleStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ruleCount"
  ): TypedContractMethod<[pool: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<
    [pool: AddressLike, paused_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "syncUser"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      user: AddressLike,
      tier: BigNumberish,
      group: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userGroup"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "userHasApass"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTier"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [pool: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "PoolPaused"
  ): TypedContractEvent<
    PoolPausedEvent.InputTuple,
    PoolPausedEvent.OutputTuple,
    PoolPausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolRegistered"
  ): TypedContractEvent<
    PoolRegisteredEvent.InputTuple,
    PoolRegisteredEvent.OutputTuple,
    PoolRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RuleAdded"
  ): TypedContractEvent<
    RuleAddedEvent.InputTuple,
    RuleAddedEvent.OutputTuple,
    RuleAddedEvent.OutputObject
  >;

  filters: {
    "PoolPaused(address,bool)": TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;
    PoolPaused: TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;

    "PoolRegistered(address)": TypedContractEvent<
      PoolRegisteredEvent.InputTuple,
      PoolRegisteredEvent.OutputTuple,
      PoolRegisteredEvent.OutputObject
    >;
    PoolRegistered: TypedContractEvent<
      PoolRegisteredEvent.InputTuple,
      PoolRegisteredEvent.OutputTuple,
      PoolRegisteredEvent.OutputObject
    >;

    "RuleAdded(address,uint16)": TypedContractEvent<
      RuleAddedEvent.InputTuple,
      RuleAddedEvent.OutputTuple,
      RuleAddedEvent.OutputObject
    >;
    RuleAdded: TypedContractEvent<
      RuleAddedEvent.InputTuple,
      RuleAddedEvent.OutputTuple,
      RuleAddedEvent.OutputObject
    >;
  };
}
